# Generated by Django 2.1 on 2018-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='image_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
