# Generated by Django 2.1 on 2018-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrx', '0002_laptops_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='ram',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
