# Generated by Django 2.1 on 2018-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrx', '0004_auto_20180830_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='lap_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
