# Generated by Django 2.1 on 2018-08-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etrx', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
    ]
