# Generated by Django 2.1 on 2018-08-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrx', '0008_remove_contact_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('lap_id', models.IntegerField()),
                ('total_cost', models.IntegerField()),
            ],
        ),
    ]
